services:
  # Backend service (FastAPI)
  - type: web
    name: fastapi-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://your-frontend-service.onrender.com  # Replace with your frontend Render URL

  # Frontend service (React)
  - type: web
    name: react-frontend
    env: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: REACT_APP_API_URL
        value: https://fastapi-backend.onrender.com  # Replace with your backend Render URL