services:
  - type: web
    name: pathfinder-ai
    env: python
    plan: free
    # Deploy from project root since main.py is there
    buildCommand: |
      # Install backend dependencies (main.py is in root)
      pip install -r requirements.txt
      # Build frontend
      cd frontend
      npm install
      npm run build
      # Verify build was created
      echo "Build contents:"
      ls -la build/
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_API_KEY
        sync: false